# Generated by Django 3.2.17 on 2023-02-06 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('house', models.CharField(max_length=250)),
                ('age', models.IntegerField()),
                ('qualification', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('star', models.CharField(max_length=250)),
                ('img', models.ImageField(upload_to='')),
                ('desc', models.TextField()),
            ],
        ),
    ]
